ae04a9 ae681f ae5f50
sdr-enthusiasts/plane-alert-db pull request #273
Opened 2023-07-13 17:40 UTC by dziban303

## Describe your changes

Added ae04a9 and ae681f, with images, and AE5F50, without. AE681F is a P-8 tactical hex but was [most recently used by 169567](https://twitter.com/SR_Planespotter/status/1679489909516820480)—this aircraft also uses AE5F50, as it did ten hours ago. Which hex the photos should go into is sort of a dilemma, but I opted to put them into the hex it was most recently using. 

Would like @Phaeton 's take on the image question. Should I add the same images to both hexes maybe? Or neither? Or the other one? Ugh

AE04A9 is an Army Citation.

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] While waiting for someone to review your request, please help review [another open pull request](https://github.com/sdr-enthusiasts/plane-alert-db/pulls) to support the maintainers.

2023-07-14 03:36 UTC, Phaeton commented
@dziban303 I would put the image on AE5F50

2023-07-14 17:48 UTC, dziban303 commented
@Phaeton done

2023-07-14 19:12 UTC, Phaeton commented
Question, should AE5F50 have the reg as 169567 vs tactical?

2023-07-14 20:18 UTC, dziban303 commented
@Phaeton done. also added pics for 🐺🐶 ae68b3. I'm done with this PR

2023-07-16 03:34 UTC, Phaeton requested changes
Found a typo on AE04A9's Type

2023-07-16 03:34 UTC, Phaeton commented on plane-alert-db.csv
> +AE04A9,99-00100,United States Army,Cess UC-35A Citation,C560,Mil,VIP Transport,Bizjet,Must Be Nice,Toy Soldiers,https://www.army.mil
```suggestion
AE04A9,99-00100,United States Army,Cessna UC-35A Citation,C560,Mil,VIP Transport,Bizjet,Must Be Nice,Toy Soldiers,https://www.army.mil

```

2023-07-16 04:07 UTC, dziban303 commented
Weird. Not sure how I managed to do that.

2023-07-16 04:59 UTC, merged