fixed Dolphin pics for AE26Ax, removed bad pics for AE269x
sdr-enthusiasts/plane-alert-db pull request #295
Opened 2023-08-24 17:56 UTC by dziban303

## Describe your changes

USCG Dolphins:
* Corrected pics where possible on hex `AE26Ax`, otherwise, removed bad pics
* Deleted bad pics on hex `AE269x`

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] While waiting for someone to review your request, please help review [another open pull request](https://github.com/sdr-enthusiasts/plane-alert-db/pulls) to support the maintainers.

2023-08-24 19:17 UTC, dziban303 commented
Done for now

2023-08-25 11:02 UTC, Phaeton requested changes
Would you update to use `/full/` versus `/400/`? I spot checked the photos and they look correct.

2023-08-25 11:43 UTC, Phaeton requested changes
Would you update  `/400/` to `/full/`? I spot checked the photos and they look correct. :helicopter:

2023-08-25 11:43 UTC, Phaeton commented on plane_images.csv
> +AE26AE,https://cdn.jetphotos.com/400/5/25018_1668386683.jpg,https://cdn.jetphotos.com/400/5/14226_1536279617.jpg,https://cdn.jetphotos.com/400/2/75250_1162534302.jpg,https://cdn.jetphotos.com/400/1/1
```suggestion
AE26AE,https://cdn.jetphotos.com/full/5/25018_1668386683.jpg,https://cdn.jetphotos.com/full/5/14226_1536279617.jpg,https://cdn.jetphotos.com/full/2/75250_1162534302.jpg,https://cdn.jetphotos.com/full/1/17801_1162916208.jpg
```

2023-08-25 11:43 UTC, Phaeton commented on plane_images.csv
> +AE26AC,https://cdn.jetphotos.com/400/5/1282233_1690414286.jpg,https://cdn.jetphotos.com/400/6/25466_1580460131.jpg,https://cdn.jetphotos.com/400/5/40798_1559415986.jpg,
```suggestion
AE26AC,https://cdn.jetphotos.com/full/5/1282233_1690414286.jpg,https://cdn.jetphotos.com/full/6/25466_1580460131.jpg,https://cdn.jetphotos.com/full/5/40798_1559415986.jpg,
```

2023-08-25 11:43 UTC, Phaeton commented on plane_images.csv
> +AE26AB,https://cdn.jetphotos.com/400/5/92669_1480542071.jpg,https://cdn.jetphotos.com/400/2/90389_1295731700.jpg,https://cdn.jetphotos.com/400/1/93650_1227247081.jpg,
```suggestion
AE26AB,https://cdn.jetphotos.com/full/5/92669_1480542071.jpg,https://cdn.jetphotos.com/full/2/90389_1295731700.jpg,https://cdn.jetphotos.com/full/1/93650_1227247081.jpg,
```

2023-08-25 11:43 UTC, Phaeton commented on plane_images.csv
> +AE26AA,https://cdn.jetphotos.com/full/5/51279_1636766293.jpg,https://cdn.jetphotos.com/400/5/56498_1568028459.jpg,https://cdn.jetphotos.com/400/6/99107_1568200328.jpg,
```suggestion
AE26AA,https://cdn.jetphotos.com/full/5/51279_1636766293.jpg,https://cdn.jetphotos.com/full/5/56498_1568028459.jpg,https://cdn.jetphotos.com/full/6/99107_1568200328.jpg,
```

2023-08-25 11:43 UTC, Phaeton commented on plane_images.csv
> +AE26A8,https://cdn.jetphotos.com/400/6/1281268_1681701698.jpg,https://cdn.jetphotos.com/400/3/95180_1361412089.jpg,https://cdn.jetphotos.com/400/2/66029_1220408566.jpg,
```suggestion
AE26A8,https://cdn.jetphotos.com/full/6/1281268_1681701698.jpg,https://cdn.jetphotos.com/full/3/95180_1361412089.jpg,https://cdn.jetphotos.com/full/2/66029_1220408566.jpg,
```

2023-08-25 11:43 UTC, Phaeton commented on plane_images.csv
> +AE26A7,https://cdn.jetphotos.com/400/6/79446_1555524694.jpg,https://cdn.jetphotos.com/400/6/64360_1540260466.jpg,https://cdn.jetphotos.com/400/2/84840_1211314794.jpg,
```suggestion
AE26A7,https://cdn.jetphotos.com/full/6/79446_1555524694.jpg,https://cdn.jetphotos.com/full/6/64360_1540260466.jpg,https://cdn.jetphotos.com/full/2/84840_1211314794.jpg,
```

2023-08-25 11:43 UTC, Phaeton commented on plane_images.csv
> +AE26A6,https://cdn.jetphotos.com/400/5/33696_1622707610.jpg,,,
```suggestion
AE26A6,https://cdn.jetphotos.com/full/5/33696_1622707610.jpg,,,
```

2023-08-25 11:43 UTC, Phaeton commented on plane_images.csv
> +AE26A4,https://cdn.jetphotos.com/400/2/96746_1039819332.jpg,https://cdn.jetphotos.com/400/1/83530_1085492344.jpg,,
```suggestion
AE26A4,https://cdn.jetphotos.com/full/2/96746_1039819332.jpg,https://cdn.jetphotos.com/full/1/83530_1085492344.jpg,,
```

2023-08-25 11:43 UTC, Phaeton commented on plane_images.csv
> +AE26A2,https://cdn.jetphotos.com/400/6/19906_1586027811.jpg,https://cdn.jetphotos.com/400/2/34371_1187482693.jpg,,
```suggestion
AE26A2,https://cdn.jetphotos.com/full/6/19906_1586027811.jpg,https://cdn.jetphotos.com/full/2/34371_1187482693.jpg,,
```

2023-08-25 11:43 UTC, Phaeton commented on plane_images.csv
> +AE26A1,https://cdn.jetphotos.com/400/5/34911_1604623866.jpg,https://cdn.jetphotos.com/400/3/63756_1317922352.jpg,https://cdn.jetphotos.com/400/2/27715_1310328358.jpg,
```suggestion
AE26A1,https://cdn.jetphotos.com/full/5/34911_1604623866.jpg,https://cdn.jetphotos.com/full/3/63756_1317922352.jpg,https://cdn.jetphotos.com/full/2/27715_1310328358.jpg,
```

2023-08-25 11:43 UTC, Phaeton commented on plane_images.csv
> +AE26A0,https://cdn.jetphotos.com/400/2/20877_1299717505.jpg,,,
```suggestion
AE26A0,https://cdn.jetphotos.com/full/2/20877_1299717505.jpg,,,
```

2023-08-25 16:21 UTC, dziban303 commented
Sorry, forgot to replace the URLs.

2023-08-25 16:22 UTC, dziban303 commented on plane_images.csv
> +AE26A0,https://cdn.jetphotos.com/400/2/20877_1299717505.jpg,,,
done

2023-08-25 16:45 UTC, Phaeton approved these changes

2023-08-25 16:45 UTC, merged