Added several planes and pictures.
sdr-enthusiasts/plane-alert-db pull request #322
Opened 2023-09-29 19:22 UTC by pmd5700

## Describe your changes

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/sdr-enthusiasts/plane-alert-db/pulls) to support the maintainers.

2023-09-29 21:47 UTC, dziban303 approved these changes

2023-09-29 21:48 UTC, dziban303 commented
looks good to me, @Phaeton can you have a look too?

2023-09-30 04:08 UTC, Phaeton requested changes

2023-09-30 04:08 UTC, Phaeton commented on plane-alert-db.csv
> +AE0EF9,83-23908,United States Army,UH-60M Blackhawk,H60,Mil,Get To The Choppa,Military Transport,Blackhawk,Toy Soldiers,https://en.wikipedia.org/wiki/Sikorsky_UH-60_Black_Hawk
```suggestion
AE0EF9,83-23908,United States Army,UH-60L Blackhawk,H60,Mil,Get To The Choppa,Military Transport,Blackhawk,Toy Soldiers,https://en.wikipedia.org/wiki/Sikorsky_UH-60_Black_Hawk

```

2023-09-30 11:58 UTC, pmd5700 commented on plane_images.csv
> +ADFF8D,https://cdn.jetphotos.com/full/6/27712_1650348168.jpg,https://cdn.jetphotos.com/full/6/34377_1551773043.jpg,https://cdn.jetphotos.com/full/6/52030_1561302932.jpg,
Good catch!

2023-09-30 12:03 UTC, pmd5700 reviewed
Incorporated changes from review. Thanks!

2023-10-01 00:27 UTC, Phaeton approved these changes

2023-10-01 00:27 UTC, merged