Adding a few craft that have flown over
sdr-enthusiasts/plane-alert-db pull request #345
Opened 2023-10-12 00:20 UTC by challgren

## Describe your changes

PLANE INFO: Adding some craft that have flown overhead

## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [X] While waiting for someone to review your request, please help review [another open pull request](https://github.com/sdr-enthusiasts/plane-alert-db/pulls) to support the maintainers.

2023-10-12 01:36 UTC, Phaeton requested changes
Got any photos for these? :innocent:

2023-10-12 01:36 UTC, Phaeton commented on plane-alert-db.csv
> +A0644D,N124TX,Texas Department of Public Safety,Aerospatiale AS-350 Ecureuil,AS50,Pol,Police Squad,Spectre 219,Speed Enforced by Aircraft,Police Forces,https://en.wikipedia.org/wiki/Eurocopter_AS350_
```suggestion
A0644D,N124TX,Texas Department of Public Safety,Eurocopter AS350 Squirrel B2,AS50,Pol,Police Squad,Spectre 219,Speed Enforced by Aircraft,Police Forces,https://w.wiki/7kcW

```

2023-10-12 01:36 UTC, Phaeton commented on plane-alert-db.csv
> +A727BD,N560JL,Express Air Medical Transport,B200 Super King Air,BE20,Civ,Air Ambo,Medical Evac,Saving Lives,Flying Doctors,https://en.wikipedia.org/wiki/Beechcraft_Super_King_Air
This one is confusing. A727BD, N560JL is a Cessna Citation V, C560. Looks to be registered to Care Flight LLC.

2023-10-12 01:38 UTC, challgren commented
> Got any photos for these? 😇

Let me see what I can come up with. Wanted to clean up my list.

2023-10-13 17:15 UTC, pmd5700 commented on plane-alert-db.csv
> +A0644D,N124TX,Texas Department of Public Safety,Aerospatiale AS-350 Ecureuil,AS50,Pol,Police Squad,Spectre 219,Speed Enforced by Aircraft,Police Forces,https://en.wikipedia.org/wiki/Eurocopter_AS350_
https://www.helis.com/spotters/zane_adams/as350b2_n124tx.jpg

2023-10-13 17:17 UTC, pmd5700 commented on plane-alert-db.csv
> +A727BD,N560JL,Express Air Medical Transport,B200 Super King Air,BE20,Civ,Air Ambo,Medical Evac,Saving Lives,Flying Doctors,https://en.wikipedia.org/wiki/Beechcraft_Super_King_Air
AE4EEE,https://cdn.jetphotos.com/full/5/12061_1441771997.jpg,,,

2023-10-13 18:57 UTC, dziban303 commented on plane-alert-db.csv
> +A727BD,N560JL,Express Air Medical Transport,B200 Super King Air,BE20,Civ,Air Ambo,Medical Evac,Saving Lives,Flying Doctors,https://en.wikipedia.org/wiki/Beechcraft_Super_King_Air
> AE4EEE,https://cdn.jetphotos.com/full/5/12061_1441771997.jpg,,,

already in the database

2023-10-15 22:06 UTC, merged