3008
sdr-enthusiasts/plane-alert-db pull request #557
Opened 2024-09-04 00:23 UTC by lingawakad

## Describe your changes

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/sdr-enthusiasts/plane-alert-db/pulls) to support the maintainers.

2024-09-04 21:15 UTC, Phaeton commented
@dziban303 You seeing an error here, or referring to the failed action run I kicked of last week?

2024-09-05 14:05 UTC, Phaeton commented
@lingawakad tag me or dzi with a review request when you are done making changes.

2024-09-05 14:07 UTC, lingawakad commented
@Phaeton any time, i'm at a good stopping point for now

2024-09-05 15:00 UTC, Phaeton requested changes

2024-09-05 15:00 UTC, Phaeton commented on plane-alert-db.csv
> +A0AB51,N142NG,Five Star Marketing,Diamond DA-42 Guardian,DA42,Civ,Surveillance,Covert,Spyplane,Oxcart,https://tinyurl.com/3yvyvhw4
why is this tagged as a Oxcart/spy plane?

2024-09-05 15:00 UTC, Phaeton commented on plane-alert-db.csv
> +A2F4E5,N29UB,JDI Holdings,MIG-29UB,MG29,Civ,Too Much Money,You Can't See Me,Aaaaaaaand It's Gone,Distinctive,https://w.wiki/3ADz
I think this would be better as a Zoomies versus Distinctive.

2024-09-05 15:00 UTC, Phaeton commented on plane-alert-db.csv
> +A062E6,N124DN,Aviation Specialty Services,Cessna 337 Super Skymaster,C337,Civ,I Am Old,Beach Life,Former USAF,Distinctive,https://w.wiki/B64a
I'd set this to Historic or Joe Cool

2024-09-05 15:00 UTC, Phaeton commented on plane-alert-db.csv
> +A00538,N100FG,University Athletic Association,Embraer Phenom 300,E55p,Civ,Egghead Eight,NCAA Div III,Sports?,As Seen on TV,https://w.wiki/B64P
```suggestion
A00538,N100FG,University Athletic Association,Embraer Phenom 300,E55P,Civ,Egghead Eight,NCAA Div III,Sports?,As Seen on TV,https://w.wiki/B64P
```

2024-09-05 15:00 UTC, Phaeton commented on plane-alert-db.csv
> +A725DF,N56PJ,Luca Aviation,Cirrus Jet Vision SF50,SF50,Civ,Safe Return,CAPS,Backpack Tadpole V-Jet,Distinctive,https://w.wiki/B3L6
I'd use Joe Cool or something other than Distinctive

2024-09-05 15:00 UTC, Phaeton commented on plane-alert-db.csv
> +A2B1D5,N273CB,Private,Beechcraft T-34,T34P,Civ,I Am Old,Retired Life,Former USAF,Distinctive,https://w.wiki/B6WK
I'd set this is Historic

2024-09-05 15:04 UTC, lingawakad commented on plane-alert-db.csv
> +A0AB51,N142NG,Five Star Marketing,Diamond DA-42 Guardian,DA42,Civ,Surveillance,Covert,Spyplane,Oxcart,https://tinyurl.com/3yvyvhw4
that's what the other DA-42s were tagged as, but i'd be fine with it going in distintive or taken out if it isn't actually distinctive

2024-09-05 15:05 UTC, lingawakad commented on plane-alert-db.csv
> +A2F4E5,N29UB,JDI Holdings,MIG-29UB,MG29,Civ,Too Much Money,You Can't See Me,Aaaaaaaand It's Gone,Distinctive,https://w.wiki/3ADz
ah good call

2024-09-05 15:10 UTC, Phaeton commented on plane-alert-db.csv
> +A0AB51,N142NG,Five Star Marketing,Diamond DA-42 Guardian,DA42,Civ,Surveillance,Covert,Spyplane,Oxcart,https://tinyurl.com/3yvyvhw4
It looks like a standard DA-42 NG, used by a small marketing firm. If its something you want to track, go ahead and put it in, but I'd tag it as As Seen on TV or something similar.

2024-09-05 15:15 UTC, lingawakad commented on plane-alert-db.csv
> +A0AB51,N142NG,Five Star Marketing,Diamond DA-42 Guardian,DA42,Civ,Surveillance,Covert,Spyplane,Oxcart,https://tinyurl.com/3yvyvhw4
no worries, i'll take it out

2024-09-05 15:16 UTC, Phaeton approved these changes

2024-09-05 15:17 UTC, merged